### PR TITLE
Update generate navigation tutorial category slug

### PR DESCRIPTION
**Pull request by ricardoaerobr**
PR created to update the following files:

- generateNavigation.js
- All indexes

### CODE REVIEW

**Review by julia-rabello — CHANGES_REQUESTED** [review]
Could we use `category` instead of `cat`? Looking at the result, it would be weird to have slugs like `cat-apps`, `cat-sellers`, `cat-shipping` 🐱

**Review by PedroAntunesCosta — APPROVED** [review]
Nice!

**Review by PedroAntunesCosta — CHANGES_REQUESTED** [review]
In the navigation.json file, tutorial categories must have type `markdown`.

**Review by julia-rabello — CHANGES_REQUESTED** [review]
PT and ES slugs should be `categoria-{categoryName}`, not `category`

**Review by julia-rabello — APPROVED** [review]

**Review by PedroAntunesCosta — APPROVED** [review]

**Pull request merged**
